=== prologin/stechec/bb5/teamroster2/data/races.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2005 U (http://www.xmlspy.com) by user user (SILOGIC) -->
<!--W3C Schema generated by XMLSpy v2005 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="apothecary">
		<xs:complexType>
			<xs:attribute name="use" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:boolean">
						<xs:enumeration value="false"/>
						<xs:enumeration value="true"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="background" type="xs:string"/>
	<xs:element name="position">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="skills"/>
			</xs:sequence>
			<xs:attribute name="qty" type="xs:byte" use="required"/>
			<xs:attribute name="title" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="cost" type="xs:long" use="required"/>
			<xs:attribute name="ma" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:byte"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="st" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:byte"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ag" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:byte"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="av" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:byte"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="normal" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="double" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="positions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="position" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="race">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="apothecary"/>
				<xs:element ref="reroll"/>
				<xs:element ref="positions"/>
				<xs:element ref="background"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Amazon"/>
						<xs:enumeration value="Chaos"/>
						<xs:enumeration value="Chaos Dwarf"/>
						<xs:enumeration value="Dark Elf"/>
						<xs:enumeration value="Dwarf"/>
						<xs:enumeration value="Elf"/>
						<xs:enumeration value="Goblin"/>
						<xs:enumeration value="Halfling"/>
						<xs:enumeration value="High Elf"/>
						<xs:enumeration value="Human"/>
						<xs:enumeration value="Khemri"/>
						<xs:enumeration value="Lizardman"/>
						<xs:enumeration value="Necromantic"/>
						<xs:enumeration value="Norse"/>
						<xs:enumeration value="Nurgle"/>
						<xs:enumeration value="Ogre"/>
						<xs:enumeration value="Orc"/>
						<xs:enumeration value="Skaven"/>
						<xs:enumeration value="Undead"/>
						<xs:enumeration value="Vampire"/>
						<xs:enumeration value="Wood Elf"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="emblem" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="races">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="race" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="BBversion" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:byte"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="reroll">
		<xs:complexType>
			<xs:attribute name="cost" type="xs:long" use="required"/>
			<xs:attribute name="qty" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:byte"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="skill">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="always hungry"/>
						<xs:enumeration value="ball and chain"/>
						<xs:enumeration value="block"/>
						<xs:enumeration value="blood lust"/>
						<xs:enumeration value="bombardier"/>
						<xs:enumeration value="bone-head"/>
						<xs:enumeration value="break tackle"/>
						<xs:enumeration value="catch"/>
						<xs:enumeration value="chainsaw"/>
						<xs:enumeration value="claws"/>
						<xs:enumeration value="dauntless"/>
						<xs:enumeration value="decay"/>
						<xs:enumeration value="dirty player"/>
						<xs:enumeration value="disturbing presence"/>
						<xs:enumeration value="dodge"/>
						<xs:enumeration value="dump off"/>
						<xs:enumeration value="foul appearance"/>
						<xs:enumeration value="frenzy"/>
						<xs:enumeration value="horns"/>
						<xs:enumeration value="hypnotic gaze"/>
						<xs:enumeration value="juggernaut"/>
						<xs:enumeration value="jump up"/>
						<xs:enumeration value="leap"/>
						<xs:enumeration value="loner"/>
						<xs:enumeration value="mighty blow"/>
						<xs:enumeration value="nerves of steel"/>
						<xs:enumeration value="no hands"/>
						<xs:enumeration value="nurgle's rot"/>
						<xs:enumeration value="pass"/>
						<xs:enumeration value="prehensile tail"/>
						<xs:enumeration value="really stupid"/>
						<xs:enumeration value="regeneration"/>
						<xs:enumeration value="right stuff"/>
						<xs:enumeration value="safe throw"/>
						<xs:enumeration value="secret weapon"/>
						<xs:enumeration value="shadowing"/>
						<xs:enumeration value="side step"/>
						<xs:enumeration value="sprint"/>
						<xs:enumeration value="stab"/>
						<xs:enumeration value="stand firm"/>
						<xs:enumeration value="strong arm"/>
						<xs:enumeration value="stunty"/>
						<xs:enumeration value="sure feet"/>
						<xs:enumeration value="sure hands"/>
						<xs:enumeration value="tackle"/>
						<xs:enumeration value="take root"/>
						<xs:enumeration value="tentacles"/>
						<xs:enumeration value="thick skull"/>
						<xs:enumeration value="throw team-mate"/>
						<xs:enumeration value="titchy"/>
						<xs:enumeration value="very long legs"/>
						<xs:enumeration value="wild animal"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="skills">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="skill" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== prologin/stechec/bb5/teamroster2/data/races.xml
<?xml version="1.0"?>
<races BBversion="5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="races.xsd">
	<race name="Amazon" emblem="amazon.jpg">
		<apothecary use="true"/>
		<reroll cost="50000" qty="8"/>
		<positions>
			<position qty="16" title="Linewomam" cost="50000" ma="6" st="3" ag="3" av="7" normal="g" double="asp">
				<skills>
					<skill name="dodge"/>
				</skills>
			</position>
			<position qty="2" title="Thrower" cost="70000" ma="6" st="3" ag="3" av="7" normal="gp" double="as">
				<skills>
					<skill name="dodge"/>
					<skill name="pass"/>
				</skills>
			</position>
			<position qty="2" title="Catcher" cost="70000" ma="6" st="3" ag="3" av="7" normal="ga" double="sp">
				<skills>
					<skill name="dodge"/>
					<skill name="catch"/>
				</skills>
			</position>
			<position qty="4" title="Blitzer" cost="90000" ma="6" st="3" ag="3" av="7" normal="gs" double="ap">
				<skills>
					<skill name="dodge"/>
					<skill name="block"/>
				</skills>
			</position>
		</positions>
		<background>Long ago, driven by a desire for adventure, the Valkyries of the Norse settlement in Lustria sailed away from their men-folk and founded a colony deep within the estuary of the river Amaxon. Now these ferocious warriors have taken to the Blood Bowl pitch and Nuffle save those who dare play against them!</background>
	</race>
	<race name="Chaos" emblem="chaos.jpg">
		<apothecary use="true"/>
		<reroll cost="60000" qty="8"/>
		<positions>
			<position qty="16" title="Beastman" cost="60000" ma="6" st="3" ag="3" av="8" normal="gsm" double="ap">
				<skills>
					<skill name="horns"/>
				</skills>
			</position>
			<position qty="4" title="Chaos warrior" cost="100000" ma="5" st="4" ag="3" av="9" normal="gsm" double="ap">
				<skills/>
			</position>
			<position qty="1" title="Minotaur" cost="150000" ma="5" st="5" ag="2" av="8" normal="sm" double="gap">
				<skills>
					<skill name="loner"/>
					<skill name="frenzy"/>
					<skill name="horns"/>
					<skill name="mighty blow"/>
					<skill name="thick skull"/>
					<skill name="wild animal"/>
				</skills>
			</position>
		</positions>
		<background>Chaos teams are not noted for the subtlety or originality of their game play. A simple drive up the centre of the pitch, maiming and injuring as many opposing players as possible, is about the limit of their game plan. They rarely, if ever, worry about such minor considerations like picking up the ball and scoring touchdowns not while there are any players left alive on the opposing team, anyway.</background>
	</race>
	<race name="Chaos Dwarf" emblem="chaosdwarves.jpg">
		<apothecary use="true"/>
		<reroll cost="70000" qty="8"/>
		<positions>
			<position qty="16" title="Hobgoblin" cost="40000" ma="6" st="3" ag="3" av="7" normal="g" double="asp">
				<skills/>
			</position>
			<position qty="6" title="Chaos dwarf" cost="70000" ma="4" st="3" ag="2" av="9" normal="gs" double="apm">
				<skills>
					<skill name="block"/>
					<skill name="tackle"/>
					<skill name="thick skull"/>
				</skills>
			</position>
			<position qty="2" title="Bull centaurs" cost="130000" ma="6" st="4" ag="2" av="9" normal="gs" double="ap">
				<skills>
					<skill name="sprint"/>
					<skill name="sure feet"/>
					<skill name="thick skull"/>
				</skills>
			</position>
			<position qty="1" title="Minotaur" cost="150000" ma="5" st="5" ag="2" av="8" normal="s" double="gapm">
				<skills>
					<skill name="loner"/>
					<skill name="frenzy"/>
					<skill name="horns"/>
					<skill name="mighty blow"/>
					<skill name="thick skull"/>
					<skill name="wild animal"/>
				</skills>
			</position>
		</positions>
		<background>Chaos Dwarfs are the twisted descendants of Dwarf explorers who have been terribly affected by the forces of Chaos, turning them into evil, self-centred creatures. In one way, however, they haven't changed at all, they still love playing Blood Bowl! Chaos Dwarfs are not very numerous and make great use of sneaky Hobgoblin slaves to perform all kinds of tasks, including playing on their Blood Bowl teams.</background>
	</race>
	<race name="Dark Elf" emblem="darkelves.jpg">
		<apothecary use="true"/>
		<reroll cost="50000" qty="8"/>
		<positions>
			<position qty="16" title="Lineman" cost="70000" ma="6" st="3" ag="4" av="8" normal="ga" double="sp">
				<skills/>
			</position>
			<position qty="2" title="Runner" cost="80000" ma="7" st="3" ag="4" av="7" normal="gap" double="s">
				<skills>
					<skill name="dump off"/>
				</skills>
			</position>
			<position qty="2" title="Assassin" cost="90000" ma="6" st="3" ag="4" av="7" normal="ga" double="sp">
				<skills>
					<skill name="shadowing"/>
					<skill name="stab"/>
				</skills>
			</position>
			<position qty="4" title="Blitzer" cost="100000" ma="7" st="3" ag="4" av="8" normal="ga" double="sp">
				<skills>
					<skill name="block"/>
				</skills>
			</position>
			<position qty="2" title="Witch elf" cost="110000" ma="7" st="3" ag="4" av="7" normal="ga" double="sp">
				<skills>
					<skill name="frenzy"/>
					<skill name="dodge"/>
					<skill name="jump up"/>
				</skills>
			</position>
		</positions>
		<background>Evil beyond belief, skilled without doubt, the Dark Elves take to the pitch to show the world their superiority. Dark Elf teams prefer a malevolent and spiteful running game over the passing of their goodly cousins. Backed up by the ruthless Witch Elves and dangerous assassins, a Dark Elf team has all the tools to power through rather than around any opposition line.</background>
	</race>
	<race name="Dwarf" emblem="dwarves.jpg">
		<apothecary use="true"/>
		<reroll cost="40000" qty="8"/>
		<positions>
			<position qty="16" title="Blocker" cost="70000" ma="4" st="3" ag="2" av="9" normal="gs" double="ap">
				<skills>
					<skill name="block"/>
					<skill name="tackle"/>
					<skill name="thick skull"/>
				</skills>
			</position>
			<position qty="2" title="Runner" cost="80000" ma="6" st="3" ag="3" av="8" normal="gp" double="as">
				<skills>
					<skill name="sure hands"/>
					<skill name="thick skull"/>
				</skills>
			</position>
			<position qty="2" title="Blitzer" cost="80000" ma="5" st="3" ag="3" av="9" normal="gs" double="ap">
				<skills>
					<skill name="block"/>
					<skill name="thick skull"/>
				</skills>
			</position>
			<position qty="2" title="Troll slayer" cost="90000" ma="5" st="3" ag="2" av="8" normal="gs" double="ap">
				<skills>
					<skill name="block"/>
					<skill name="dauntless"/>
					<skill name="frenzy"/>
					<skill name="thick skull"/>
				</skills>
			</position>
			<position qty="1" title="Deathroller" cost="160000" ma="4" st="7" ag="1" av="10" normal="s" double="gap">
				<skills>
					<skill name="break tackle"/>
					<skill name="dirty player"/>
					<skill name="juggernaut"/>
					<skill name="mighty blow"/>
					<skill name="no hands"/>
					<skill name="secret weapon"/>
					<skill name="stand firm"/>
				</skills>
			</position>
		</positions>
		<background>Dwarfs seem to be ideal Blood Bowl players, being compact, tough, well-armoured and having a stubborn knack of refusing to die! Most successful Dwarf teams work to the principle that if they can take out all the other team's potential scorers, and wear down the rest, then there won't be anybody left to stop them scoring the winning touchdowns!</background>
	</race>
	<race name="Elf" emblem="elves.jpg">
		<apothecary use="true"/>
		<reroll cost="50000" qty="8"/>
		<positions>
			<position qty="16" title="Lineman" cost="60000" ma="6" st="3" ag="4" av="7" normal="ga" double="sp">
				<skills/>
			</position>
			<position qty="2" title="Thrower" cost="70000" ma="6" st="3" ag="4" av="7" normal="gap" double="s">
				<skills>
					<skill name="pass"/>
				</skills>
			</position>
			<position qty="4" title="Catcher" cost="100000" ma="8" st="3" ag="4" av="7" normal="ga" double="sp">
				<skills>
					<skill name="catch"/>
					<skill name="nerves of steel"/>
				</skills>
			</position>
			<position qty="2" title="Blitzer" cost="110000" ma="7" st="3" ag="4" av="8" normal="ga" double="sp">
				<skills>
					<skill name="block"/>
					<skill name="side step"/>
				</skills>
			</position>
		</positions>
		<background>When the NAF collapsed, many Elven teams were left penniless. Those teams that have survived the fallout are not as rich as the High Elf teams nor as well equipped, but they sure know how to play the game. Sporting facemasks and mohawks, they take to the pitch to relive the glory days they once played in.</background>
	</race>
	<race name="Goblin" emblem="goblins.jpg">
		<apothecary use="true"/>
		<reroll cost="60000" qty="8"/>
		<positions>
			<position qty="16" title="Goblin" cost="40000" ma="6" st="2" ag="3" av="7" normal="a" double="gsp">
				<skills>
					<skill name="dodge"/>
					<skill name="right stuff"/>
					<skill name="stunty"/>
				</skills>
			</position>
			<position qty="1" title="Bombardier" cost="40000" ma="6" st="2" ag="3" av="7" normal="a" double="gsp">
				<skills>
					<skill name="bombardier"/>
					<skill name="dodge"/>
					<skill name="no hands"/>
					<skill name="secret weapon"/>
					<skill name="stunty"/>
				</skills>
			</position>
			<position qty="1" title="Pogoer" cost="40000" ma="7" st="2" ag="3" av="7" normal="a" double="gsp">
				<skills>
					<skill name="dirty player"/>
					<skill name="dodge"/>
					<skill name="leap"/>
					<skill name="secret weapon"/>
					<skill name="stunty"/>
					<skill name="very long legs"/>
				</skills>
			</position>
			<position qty="1" title="Looney" cost="40000" ma="6" st="2" ag="3" av="7" normal="a" double="gsp">
				<skills>
					<skill name="chainsaw"/>
					<skill name="no hands"/>
					<skill name="secret weapon"/>
