=== prologin/stechec/bb5/teamroster2/data/team.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2005 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="name" type="xs:string"/>
	<xs:element name="coach" type="xs:string"/>
	<xs:element name="ag" type="xs:byte"/>
	<xs:element name="apothecary" type="xs:byte"/>
	<xs:element name="assistant" type="xs:byte"/>
	<xs:element name="av" type="xs:byte"/>
	<xs:element name="bank" type="xs:long"/>
	<xs:element name="cas" type="xs:byte"/>
	<xs:element name="cheerleader" type="xs:byte"/>
	<xs:element name="com" type="xs:byte"/>
	<xs:element name="cost" type="xs:long"/>
	<xs:element name="fanfactor" type="xs:byte"/>
	<xs:element name="inj" type="xs:string"/>
	<xs:element name="int" type="xs:byte"/>
	<xs:element name="ma" type="xs:byte"/>
	<xs:element name="mpv" type="xs:byte"/>
	<xs:element name="player">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ma"/>
				<xs:element ref="st"/>
				<xs:element ref="ag"/>
				<xs:element ref="av"/>
				<xs:element ref="cost"/>
				<xs:element ref="skills"/>
				<xs:element ref="inj"/>
				<xs:element ref="com"/>
				<xs:element ref="td"/>
				<xs:element ref="int"/>
				<xs:element ref="cas"/>
				<xs:element ref="mpv"/>
				<xs:element ref="spp"/>
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="toto"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="number" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:byte">
						<xs:enumeration value="1"/>
						<xs:enumeration value="2"/>
						<xs:enumeration value="3"/>
						<xs:enumeration value="4"/>
						<xs:enumeration value="5"/>
						<xs:enumeration value="6"/>
						<xs:enumeration value="7"/>
						<xs:enumeration value="8"/>
						<xs:enumeration value="9"/>
						<xs:enumeration value="10"/>
						<xs:enumeration value="11"/>
						<xs:enumeration value="12"/>
						<xs:enumeration value="13"/>
						<xs:enumeration value="14"/>
						<xs:enumeration value="15"/>
						<xs:enumeration value="16"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="position" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="display" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="players">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="player"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="reroll" type="xs:byte"/>
	<xs:element name="rerollcost" type="xs:long"/>
	<xs:element name="skill">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="always hungry"/>
				<xs:enumeration value="ball and chain"/>
				<xs:enumeration value="block"/>
				<xs:enumeration value="blood lust"/>
				<xs:enumeration value="bombardier"/>
				<xs:enumeration value="bone-head"/>
				<xs:enumeration value="break tackle"/>
				<xs:enumeration value="catch"/>
				<xs:enumeration value="chainsaw"/>
				<xs:enumeration value="claws"/>
				<xs:enumeration value="dauntless"/>
				<xs:enumeration value="decay"/>
				<xs:enumeration value="dirty player"/>
				<xs:enumeration value="disturbing presence"/>
				<xs:enumeration value="dodge"/>
				<xs:enumeration value="dump off"/>
				<xs:enumeration value="foul appearance"/>
				<xs:enumeration value="frenzy"/>
				<xs:enumeration value="horns"/>
				<xs:enumeration value="hypnotic gaze"/>
				<xs:enumeration value="juggernaut"/>
				<xs:enumeration value="jump up"/>
				<xs:enumeration value="leap"/>
				<xs:enumeration value="loner"/>
				<xs:enumeration value="mighty blow"/>
				<xs:enumeration value="nerves of steel"/>
				<xs:enumeration value="no hands"/>
				<xs:enumeration value="nurgle's rot"/>
				<xs:enumeration value="pass"/>
				<xs:enumeration value="prehensile tail"/>
				<xs:enumeration value="really stupid"/>
				<xs:enumeration value="regeneration"/>
				<xs:enumeration value="right stuff"/>
				<xs:enumeration value="safe throw"/>
				<xs:enumeration value="secret weapon"/>
				<xs:enumeration value="shadowing"/>
				<xs:enumeration value="side step"/>
				<xs:enumeration value="sprint"/>
				<xs:enumeration value="stab"/>
				<xs:enumeration value="stand firm"/>
				<xs:enumeration value="strong arm"/>
				<xs:enumeration value="stunty"/>
				<xs:enumeration value="sure feet"/>
				<xs:enumeration value="sure hands"/>
				<xs:enumeration value="tackle"/>
				<xs:enumeration value="take root"/>
				<xs:enumeration value="tentacles"/>
				<xs:enumeration value="thick skull"/>
				<xs:enumeration value="throw team-mate"/>
				<xs:enumeration value="titchy"/>
				<xs:enumeration value="very long legs"/>
				<xs:enumeration value="wild animal"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="skills">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="skill" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="spp" type="xs:byte"/>
	<xs:element name="st" type="xs:byte"/>
	<xs:element name="td" type="xs:byte"/>
	<xs:element name="team">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="coach"/>
				<xs:element ref="bank"/>
				<xs:element ref="reroll"/>
				<xs:element ref="rerollcost"/>
				<xs:element ref="fanfactor"/>
				<xs:element ref="assistant"/>
				<xs:element ref="cheerleader"/>
				<xs:element ref="apothecary"/>
				<xs:element ref="players"/>
			</xs:sequence>
			<xs:attribute name="race" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Amazon"/>
						<xs:enumeration value="Chaos"/>
						<xs:enumeration value="Chaos Dwarf"/>
						<xs:enumeration value="Dark Elf"/>
						<xs:enumeration value="Dwarf"/>
						<xs:enumeration value="Elf"/>
						<xs:enumeration value="Goblin"/>
						<xs:enumeration value="Halfling"/>
						<xs:enumeration value="High Elf"/>
						<xs:enumeration value="Human"/>
						<xs:enumeration value="Khemri"/>
						<xs:enumeration value="Lizardman"/>
						<xs:enumeration value="Necromantic"/>
						<xs:enumeration value="Norse"/>
						<xs:enumeration value="Nurgle"/>
						<xs:enumeration value="Ogre"/>
						<xs:enumeration value="Orc"/>
						<xs:enumeration value="Skaven"/>
						<xs:enumeration value="Undead"/>
						<xs:enumeration value="Vampire"/>
						<xs:enumeration value="Wood Elf"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="BBversion" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:byte"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="emblem" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== prologin/stechec/bb5/data/team/chaos.xml
<?xml version="1.0" encoding="iso-8859-1" ?> <!-- -*-SGML-*- -->

<team bb_version="5" race="Chaos" emblem="amazon.png"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="file:///home/kapouik/tbt/local/share/stechec/bb5/schema/team.xsd">

  <formation>default.xml</formation>
  <name>The night before nightmare</name>
  <coach>The Dead</coach>
  <rating>100</rating>
  <treasury>0</treasury>
  <reroll>2</reroll>
  <rerollcost>40000</rerollcost>
  <fanfactor>7</fanfactor>
  <assistant>0</assistant>
  <cheerleader>0</cheerleader>
  <apothecary>1</apothecary>
  
  <players>

    <!-- Blitzer 3*90 = 270 -->
    <player name="Warrior01" number="1" position="Blitzer" display="amazon_b.png">
      <positionid>4</positionid>
      <ma>6</ma>
      <st>3</st>
      <ag>3</ag>
      <av>8</av>
      <cost>60000</cost>
      <skill>Block</skill>
      <skill>Dodge</skill>
      <com>0</com>
      <int>0</int>
      <td>0</td>
      <cas>0</cas>
      <mpv>0</mpv>
      <spp>0</spp>
    </player>

    <player name="Mary-Jean" number="2" position="Blitzer" display="amazon_b.png">
      <positionid>4</positionid>
      <ma>6</ma>
      <st>3</st>
      <ag>3</ag>
      <av>8</av>
      <cost>60000</cost>
      <skill>Block</skill>
      <skill>Dodge</skill>
      <com>0</com>
      <int>0</int>
      <td>0</td>
      <cas>0</cas>
      <mpv>0</mpv>
      <spp>0</spp>
    </player>

    <player name="Mary-Carol" number="3" position="Blitzer" display="amazon_b.png">
      <positionid>4</positionid>
      <ma>6</ma>
      <st>3</st>
      <ag>3</ag>
      <av>8</av>
      <cost>60000</cost>
      <skill>Block</skill>
      <skill>Dodge</skill>
      <com>0</com>
      <int>0</int>
      <td>0</td>
      <cas>0</cas>
      <mpv>0</mpv>
      <spp>0</spp>
    </player>

<!-- Thrower 2*70 = 140 -->
    <player name="Jacinthe" number="4" position="Thrower" display="amazon_t.png">
      <positionid>4</positionid>
      <ma>5</ma>
      <st>4</st>
      <ag>3</ag>
      <av>9</av>
      <cost>100000</cost>
      <com>0</com>
      <int>0</int>
      <td>0</td>
      <cas>0</cas>
      <mpv>0</mpv>
      <spp>0</spp>
    </player>

    <player name="Tulip" number="5" position="Thrower" display="amazon_t.png">
      <positionid>4</positionid>
      <ma>5</ma>
      <st>4</st>
      <ag>3</ag>
      <av>9</av>
      <cost>100000</cost>
      <com>0</com>
      <int>0</int>
      <td>0</td>
      <cas>0</cas>
      <mpv>0</mpv>
      <spp>0</spp>
    </player>

<!-- Catcher 2*70 = 140 -->
    <player name="Purple" number="6" position="Catcher" display="amazon_c.png">
      <positionid>4</positionid>
      <ma>5</ma>
      <st>4</st>
      <ag>3</ag>
      <av>9</av>
      <cost>100000</cost>
      <com>0</com>
      <int>0</int>
      <td>0</td>
      <cas>0</cas>
      <mpv>0</mpv>
      <spp>0</spp>
    </player>

    <player name="Magenta" number="7" position="Catcher" display="amazon_c.png">
      <positionid>4</positionid>
      <ma>5</ma>
      <st>4</st>
      <ag>3</ag>
      <av>9</av>
      <cost>100000</cost>
      <com>0</com>
      <int>0</int>
      <td>0</td>
      <cas>0</cas>
      <mpv>0</mpv>
      <spp>0</spp>
    </player>

<!-- Linewomen 5*50 = 250 -->
    <player name="Anna" number="7" position="Linewoman" display="amazon_l.png">
      <positionid>4</positionid>
      <ma>5</ma>
      <st>4</st>
      <ag>3</ag>
      <av>9</av>
      <cost>100000</cost>
      <skill>Dodge</skill>
      <skill>Block</skill>
      <com>0</com>
      <int>0</int>
      <td>0</td>
      <cas>0</cas>
      <mpv>0</mpv>
      <spp>0</spp>
    </player>

    <player name="Martina" number="8" position="Linewoman" display="amazon_l.png">
      <positionid>4</positionid>
      <ma>6</ma>
      <st>3</st>
      <ag>3</ag>
      <av>8</av>
      <cost>60000</cost>
      <skill>Dodge</skill>
      <skill>Block</skill>
      <com>0</com>
      <int>0</int>
      <td>0</td>
      <cas>0</cas>
      <mpv>0</mpv>
      <spp>0</spp>
    </player>

    <player name="Serena" number="9" position="Linewoman" display="amazon_l.png">
      <positionid>4</positionid>
      <ma>6</ma>
      <st>3</st>
      <ag>3</ag>
      <av>8</av>
      <cost>60000</cost>
      <skill>Dodge</skill>
      <skill>Block</skill>
      <com>0</com>
      <int>0</int>
      <td>0</td>
      <cas>0</cas>
      <mpv>0</mpv>
      <spp>0</spp>
    </player>

    <player name="Jelena" number="10" position="Linewoman" display="amazon_l.png">
      <positionid>4</positionid>
      <ma>6</ma>
      <st>3</st>
      <ag>3</ag>
      <av>8</av>
      <cost>60000</cost>
      <skill>Dodge</skill>
      <skill>Block</skill>
      <com>0</com>
      <int>0</int>
      <td>0</td>
      <cas>0</cas>
      <mpv>0</mpv>
      <spp>0</spp>
    </player>

    <player name="Iva" number="11" position="Linewoman" display="amazon_l.png">
      <positionid>4</positionid>
      <ma>5</ma>
      <st>5</st>
      <ag>2</ag>
      <av>8</av>
      <cost>150000</cost>
      <skill>Dodge</skill>
      <skill>Block</skill>
      <skill>Pass</skill>
      <com>0</com>
      <int>0</int>
      <td>0</td>
      <cas>0</cas>
      <mpv>0</mpv>
      <spp>0</spp>
   </player>

  </players>
</team>
