=== prologin/stechec/conf/config.dtd
<?xml version="1.0" encoding="iso-8859-1" ?>

<!ELEMENT config (game?, client*, server?)>

<!ELEMENT game (nb_team, player_per_team?, max_turn?, map?)>
  <!ELEMENT nb_team (#PCDATA)>
    <!ATTLIST nb_team player_per_team CDATA "1">
  <!ELEMENT max_turn (#PCDATA)>
  <!ELEMENT map (#PCDATA)>

<!ELEMENT client (rules?, champion?, connect?, team?, mode?, limit?, debug?, redirection?)>
  <!ATTLIST client id CDATA "0">
  <!ELEMENT rules (#PCDATA)>
  <!ELEMENT champion (#PCDATA)>
  <!ELEMENT connect EMPTY>
    <!ATTLIST connect val (network|standalone) "network">
    <!ATTLIST connect host CDATA "localhost">
    <!ATTLIST connect port CDATA "25151">
    <!ATTLIST connect game_uid CDATA "42">
    <!ATTLIST connect connect_on_startup (true|false) "true">
  <!ELEMENT team (#PCDATA)>
  <!ELEMENT mode EMPTY>
    <!ATTLIST mode replay (true|false) "false">
    <!ATTLIST mode spectator (true|false) "false">
    <!ATTLIST mode file CDATA "">
  <!ELEMENT limit EMPTY>
    <!ATTLIST limit memory CDATA "0">
    <!ATTLIST limit time CDATA "0">
    <!ATTLIST limit time_reserve CDATA "0">
  <!ELEMENT debug EMPTY>
    <!ATTLIST debug valgrind (true|false) "false">
    <!ATTLIST debug gdb (true|false) "false">
    <!ATTLIST debug verbose CDATA "2">
    <!ATTLIST debug printloc (true|false) "false">
  <!ELEMENT redirection EMPTY>
    <!ATTLIST redirection stdin CDATA #IMPLIED>
    <!ATTLIST redirection stdout CDATA #IMPLIED>
 

<!ELEMENT server (rules?, options, listen, log, nb_spectator, debug, server_debug)>
  <!ELEMENT options EMPTY>
    <!ATTLIST options persistent (true|false) "true">
    <!ATTLIST options wait_timeout CDATA "30">
    <!ATTLIST options start_game_timeout CDATA "30">
  <!ELEMENT listen EMPTY>
    <!ATTLIST listen port CDATA "25151">
  <!ELEMENT log EMPTY>
    <!ATTLIST log enabled (true|false) "false">
    <!ATTLIST log file CDATA "match.log">
  <!ELEMENT nb_spectator (#PCDATA)>
  <!ELEMENT server_debug EMPTY>
    <!ATTLIST server_debug verbose CDATA "2">
    <!ATTLIST server_debug printloc (true|false) "false">

=== prologin/stechec/stechec/tools/xml_test/config.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE config SYSTEM "config.dtd">
<config>

  <game>
    <nb_team>2</nb_team>
  </game>

  <client>
    <rules>bb5_client_rules</rules>
    <connect host="localhost" port="25151" connect_on_startup="true" />
  </client>

  <client id="1">
    <champion>bb5_visu</champion>
    <team>team.xml</team>
    <mode replay="false" spectator="false" />
    <limit memory="10000" time="500" time_reserve="2500" />
    <debug valgrind="false" gdb="false" verbose="4" printloc="true" />
  </client>

  <client id="2">
    <champion>bb5_client_console</champion>
    <team>team.xml</team>
    <mode replay="false" file="match.log" spectator="false" />
    <limit memory="0" time="500" time_reserve="2500" />
    <debug valgrind="false" gdb="false" verbose="8" printloc="true" />
  </client>

  <server>
    <rules>bb5_arbiter</rules>
    <options persistent="true" start_game_timeout="30" />
    <listen port="25151" />
    <log enabled="false" file="match.log" />
    <nb_spectator>0</nb_spectator>
    <debug verbose="2" printloc="false" />
    <server_debug verbose="3" printloc="false" />
  </server>

</config>

=== prologin/stechec/prologin/prolo2007/data/config_prolo.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE config SYSTEM "file:///opt/stechec/share/stechec/config.dtd">

<!--

C'est dans ce fichier que vous configurerez votre match.
Vous devez definir le nombre d'equipe (une equipe etant en fait
un champion), le nombre de tours a jouer, ainsi que la carte a
utiliser.

Ensuite, vous devez definir autant de clients que d'equipe.
Dans ce fichier, nous avons configure 5 equipes, et on retrouve
effectivement 5 sections <client id="n"> ... </client>.

L'interface graphique est aussi un client, mais n'est pas compte
comme une equipe. Si vous souhaitez la desactiver, pour faire par
exemple une grande serie de matchs, il vous suffit de supprimer
ou de commenter la section correspondante (ici, celle d'id 6).
Il est important de modifier nb_spectator dans la section server.

N'hesitez pas a poser vos questions sur le forum de Prologin.

!-->

<config>

  <game>
    <nb_team>5</nb_team>      <!-- Nombre de champions sur la map                       !-->
    <max_turn>400</max_turn>  <!-- Nombre de tours a jouer                              !-->
    <map>arena10.map</map>    <!-- Map dispos dans /opt/stechec/share/stechec/prolo2007 !-->
  </game>

  <client>
    <rules>globulus</rules>
    <connect val="network" host="127.0.0.1" port="25150"
             game_uid="40" connect_on_startup="true" />
  </client>

<!--
Ici, vous devez definir le chemin vers votre champion, qui est
le fichier .so genere par le Makefile.
En tournoi, vous aurez cinq instances de votre champion par map,
soit en tout 10 champions sur la carte.
Note : il ne faut *pas* mettre le .so a la fin. L'extension varie d'un
       systeme a l'autre, notre programme la determine donc tout seul.
!-->
  <client id="1">
    <champion>/opt/stechec/champions/champion</champion>
    <mode replay="false" spectator="false" />
    <limit memory="10000" time="500" time_reserve="2500" />
    <debug valgrind="false" gdb="false" verbose="3" printloc="true" />
  </client>

  <client id="2">
    <champion>/opt/stechec/champions/champion</champion>
    <mode replay="false" spectator="false" />
    <limit memory="10000" time="500" time_reserve="2500" />
    <debug valgrind="false" gdb="false" verbose="3" printloc="true" />
  </client>

  <client id="3">
    <champion>/opt/stechec/champions/champion</champion>
    <mode replay="false" spectator="false" />
    <limit memory="10000" time="500" time_reserve="2500" />
    <debug valgrind="false" gdb="false" verbose="3" printloc="true" />
  </client>

  <client id="4">
    <champion>/opt/stechec/champions/champion</champion>
    <mode replay="false" spectator="false" />
    <limit memory="10000" time="500" time_reserve="2500" />
    <debug valgrind="false" gdb="false" verbose="3" printloc="true" />
  </client>

  <client id="5">
    <champion>/opt/stechec/champions/champion</champion>
    <mode replay="false" spectator="false" />
    <limit memory="10000" time="500" time_reserve="2500" />
    <debug valgrind="false" gdb="false" verbose="3" printloc="true" />
  </client>

<!--
Ce client est l'interface graphique. Pour la desactiver, il suffit
de supprimer l'entree, et de changer la valeur de nb_spectators
dans la section "server", un peu plus bas.
!-->
<!--  <client id="6">
    <champion>globulus_sdlvisu</champion>
    <mode replay="false" file="match.log" spectator="true" />
    <limit memory="0" time="500" time_reserve="2500" />
    <debug valgrind="false" gdb="false" verbose="3" printloc="true" />
    <screen res_x="800" res_y="600" />
  </client>
!-->
  <server>
    <rules>globulus</rules>
    <options persistent="false" start_game_timeout="30" />
    <listen port="25150" />
    <log enabled="false" file="match.log" />
    <nb_spectator>0</nb_spectator>
    <debug verbose="8" printloc="true" />
    <server_debug verbose="3" printloc="false" />
  </server>

</config>

=== prologin/stechec/prologin/prolo2007/data/config_2_teams_3_players.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE config SYSTEM "file:///home/ghalaax/stechec/trunk/install/share/stechec/config.dtd">

<config>

  <game>
    <nb_team>3</nb_team>
    <max_turn>30</max_turn>
    <map>simple.map</map>
  </game>

  <client>
    <rules>globulus</rules>
    <connect val="network" host="127.0.0.1" port="25150"
             game_uid="40" connect_on_startup="true" />
  </client>

  <client id="666">
    <champion>/home/ghalaax/stechec/trunk/install/interfaces/c/champion</champion>
    <mode replay="false" spectator="false" />
    <limit memory="100000" time="500" time_reserve="2500" />
    <debug valgrind="false" gdb="false" verbose="8" printloc="true" />
  </client>

  <client id="665">
    <champion>/home/ghalaax/stechec/trunk/install/interfaces/c/champion</champion>
    <mode replay="false" spectator="false" />
    <limit memory="100000" time="500" time_reserve="2500" />
    <debug valgrind="false" gdb="false" verbose="8" printloc="true" />
  </client>

  <server>
    <rules>globulus</rules>
    <options persistent="true" start_game_timeout="30" />
    <listen port="25150" />
    <log enabled="false" file="match.log" />
    <nb_spectator>0</nb_spectator>
    <debug verbose="8" printloc="true" />
    <server_debug verbose="3" printloc="false" />
  </server>

</config>
